### PR TITLE
to do list app

### PR DESCRIPTION
**Pull request by zkr024**
Copy to-do list app.
Code partner needs to check the project and check if changes need to be made.
JS best practices prtocedures

### CODE REVIEW

**Comment by Gnwin** [comment]
-  The button in line 21 of your index.html in your src folder to add an activity doesn't have functionality.
Consider creating a form and adding an event listener(submit).


- In ./src/modules/eventListeners.js
Usage of keycode on lines 9,37 and 43 is not recommended because it is unstable. Consider using a key.


- In /src/modules/eventListeners.js
There are repeated lines of code.
Lines - 59,60,61
Lines - 66,67,68
Use the dry principle to avoid repeating code on this lines

**Comment by zkr024** [comment]
> * The button in line 21 of your index.html in your src folder to add an activity doesn't have functionality.
>   Consider creating a form and adding an event listener(submit).
> * In ./src/modules/eventListeners.js
>   Usage of keycode on lines 9,37 and 43 is not recommended because it is unstable. Consider using a key.
> * In /src/modules/eventListeners.js
>   There are repeated lines of code.
>   Lines - 59,60,61
>   Lines - 66,67,68
>   Use the dry principle to avoid repeating code on this lines

@Gnwin Thank you for the feedback, I'll work on it.

**Comment by Gnwin** [comment]
Approved. Nothing to change, your project is complete. You can go on and merge.

**Review by Gnwin — APPROVED** [review]
Approved. Nothing else to change. You can go on and merge.

**Pull request merged**
